### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by tirinox** [Adamdad/keras-YOLOv3-mobilenet#1]
Hello. Please explain how to use your fork?
Do I need pretrained weight for mobile net?
You also mentioned train.txt and val.txt, but they are not present.
Please help, because it's really interesting.

**Comment by Adamdad** [comment]
1. there is no need to worry about the pretrained weight because I build the model on 'keras_appilcation'.When you create the model, the  pretrained weight would be load automaticly
2. val.txt is just in the same format as train.txt, which is specified below
