### ISSUE TITLE
raise IOError("Couldn't open webcam or video")

### ISSUE THREAD

**Issue by nuannuan1991** [Adamdad/keras-YOLOv3-mobilenet#2]
Dear Adamdad:
Thank you for your hard work!!!
when I executed the command: python yolo_video.py，but there is an errorr: aise IOError("Couldn't open webcam or video").
while, I have tested that the camera is good.
what's more, i have installed opencv3.4， tf2.0, and yolov3.weights is also have changed well.
what should i do??
Greatful! !

**Comment by Adamdad** [comment]
you may like this https://github.com/qqwweee/keras-yolo3/issues/149

**Comment by nuannuan1991** [comment]
@Adamdad 
Hi Adamdad,I modified it according to your code, while there is an error.
def detect_video(yolo, video_path, output_path=""):
import cv2
VIDEO_NAME = 'video1.mp4'
CWD_PATH = os.getcwd()
PATH_TO_VIDEO = os.path.join(CWD_PATH,VIDEO_NAME)
vid = cv2.VideoCapture(PATH_TO_VIDEO)
if not vid.isOpened():
raise IOError("Couldn't open webcam or video")
I tried many times these days, but still can't solve it.I wonder how you did it.
