### ISSUE TITLE
Comparison between yolo_body and tiny_yolo?

### ISSUE THREAD

**Issue by ZHANGKEON** [Adamdad/keras-YOLOv3-mobilenet#4]
Have you compare the accuracy between yolo_body (mobilenet + yolov3) and tiny_yolo (directly use tiny yolov3)?

**Comment by Adamdad** [comment]
I haven't done yet. You can have a try on that but I believe that Mobilenet is better than the tiny-yolo on all aspects

**Comment by ZHANGKEON** [comment]
Agreed. I still has two quations:
(1) What is the accuracy (mAP) and speed (FPS) of the yolov3 with mobilenet?
(2) Have you considered the modification of other conv layers (layer 53-75) except the feature extractor (darknet53)?

**Comment by shenyingying** [comment]
> Agreed. I still has two questions:
> (1) What is the accuracy (mAP) and speed (FPS) of the yolov3 with mobilenet?
> (2) Have you considered the modification of other conv layers (layer 53-75) except the feature extractor (darknet53)?

i have modification the structure of layers,about 20+

**Comment by Lynnee123** [comment]
>           I haven't done yet. You can have a try on that but I believe that Mobilenet is better than the tiny-yolo on all aspects

I tested YOLOv3-MobileNet both in accuracy and speed,It's strange，Nither of them are  bertter then YOLOv3-darknet53's.I don't know what's wrong with it. Can you help me? Thank you so much!

**Comment by Adamdad** [comment]
I have met the same question before. If you are testing on a simple dataset that both backends can achieve good performance(MAP above 90%), mobilenet could be a better model because its ability is enough to learn the pattern in the dataset. In such case, darknet53 is too deep. But if the performance of yolov3-mobilenet is better by large, the results are confusing.

**Comment by Lynnee123** [comment]
>           I have met the same question before. If you are testing on a simple dataset that both backends can achieve good performance(MAP above 90%), mobilenet could be a better model because its ability is enough to learn the pattern in the dataset. In such case, darknet53 is too deep. But if the performance of yolov3-mobilenet is better by large, the results are confusing.



>           I have met the same question before. If you are testing on a simple dataset that both backends can achieve good performance(MAP above 90%), mobilenet could be a better model because its ability is enough to learn the pattern in the dataset. In such case, darknet53 is too deep. But if the performance of yolov3-mobilenet is better by large, the results are confusing.

Thank you very much for your answer.I selected 20,000 + pictures from the bdd100k dataset for training, and tested picture with 1280x720 in size. As for TIAN X, it took about 0.4 seconds to process one picture, but the effect was not very good
