### ISSUE TITLE
About the input_shape of the model

### ISSUE THREAD

**Issue by zhangyufei1995** [Adamdad/keras-YOLOv3-mobilenet#41]
Will the input of the model mobilenet-yolov3 be 320*320? But why did you write 416*416 here?
![image](https://user-images.githubusercontent.com/45422726/57570271-b8418800-7432-11e9-8413-9435c2c3fcf8.png)

**Comment by Adamdad** [comment]
I am just using a typical input size(like 416 416) to estimate the feature size when write the code. The only constraint of the inputsize is that it must be the multiple of 32

**Comment by Hugsy19** [comment]
> 
> 
> I am just using a typical input size(like 416 416) to estimate the feature size when write the code. The only constraint of the inputsize is that it must be the multiple of 32

I have trained a model with input_size=320, but the test result of input_size=320 is bad than input_size=416, why?

**Comment by Adamdad** [comment]
It no surprise that smaller input size always decreases the performance of DL algorithm.

**Comment by Hugsy19** [comment]
> 
> 
> It no surprise that smaller input size always decreases the performance of DL algorithm.
I see, Thank you~
