### ISSUE TITLE
the weight file's layer is different to the model's layer

### ISSUE THREAD

**Issue by autogyro** [Adamdad/keras-YOLOv3-mobilenet#5]
hello Adamdad
I try to run the yolo-mobilenet.py, I got the following message, I used the weight that automatic downloaded, named as mobilenet_1_0_224_tf.h5
and i modified that at yolo-mobilenet.py  as the following:

class YOLO(object):
    def __init__(self):
        self.model_path = 'model_data/mobilenet_1_0_224_tf.h5' # model path or trained weights path 
---------------------error messages--------------------
  File "D:\Anaconda3\lib\site-packages\keras\engine\saving.py", line 900, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 55 layers into a model with 97 layers.

cheers
Edward

**Comment by Adamdad** [comment]
you know, the pre-trained model of mobilenet can not loaded as the model of yolo. yolo makes extra layers to make feature fusion across scales. So the structure of YOLOv3-mobilenet is not the same as mobilenet itself. you need to train the pre-trained model on your own dataset before test it.
