### ISSUE TITLE
Do you test on public dataset?

### ISSUE THREAD

**Issue by qiang92** [Adamdad/keras-YOLOv3-mobilenet#6]
Like VOC07 or COCO, and what about your FPS on 1080Ti or others?

**Comment by OblivionStaff** [comment]
I use VOC2012+07 trainval as training data, get a mAP 0.66 on 07 test. Maybe it is low compared to mobilenet ssd (0.78)

**Comment by OblivionStaff** [comment]
> I use VOC2012+07 trainval as training data, get a mAP 0.66 on 07 test. Maybe it is low compared to mobilenet ssd (0.78)

I was wrong. Without COCO pre-training, the mAP of  mobilenet ssd is about 0.68

**Comment by Adamdad** [comment]
what is your resolution you are using and mobilenet-ssd used?

**Comment by OblivionStaff** [comment]
> what is your resolution you are using and mobilenet-ssd used?

the resolution is 320 and the mAP of mobilenet-ssd is reported [here](https://github.com/chuanqi305/MobileNet-SSD#reproduce-the-result)

**Comment by Adamdad** [comment]
what about the FPS?

**Comment by nvnnghia** [comment]
any updates?
